variables:
    IMAGE_NAME: abdallahatef/odoo
    IMAGE_TAG: odoo-1.0

stages:
    - test
    - build
    - deploy


run_test:
    stage: test
    image: ubuntu:22.04
    before_script:
        - apt-get update && apt-get install make && apt-get install -y python3-setuptools && apt-get install -y python-setuptools && python3 setup.py sdist && apt install postgresql postgresql-client && sed -n -e '/^Depends:/,/^Pre/ s/ python3-\(.*\),/python3-\1/p' debian/control | sudo xargs apt-get install -y && apt-get install -y build-essential && apt-get install -y manpages-dev && sudo -u postgres createuser -d -R -S $USER && createdb $USER
    script:
        - python3 odoo-bin --addons-path=addons -d mydb



build_image:
    stage: build
    image: docker:24.0.7
    services:
        - docker:24.0.7-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
    # script:
    #     - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@3.239.93.125 "
    #         sudo apt install -y docker.io;
    #         sudo usermod -aG docker ubuntu;
    #         sudo systemctl restart docker;
    #         docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
    #         docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG &&
    #         echo $USER "
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@54.166.173.204 "
            git clone https://github.com/abdula8/odoo.git
            cd odoo &&
            sudo apt-get update &&
            sudo apt-get install make &&
            sudo apt-get install -y python3-setuptools &&
            sudo apt-get install -y python-setuptools &&
            python3 setup.py sdist &&
            sed -n -e '/^Depends:/,/^Pre/ s/ python3-\(.*\),/python3-\1/p' debian/control | sudo xargs apt-get install -y &&
            apt-get install -y build-essential &&
            sudo apt-get install -y manpages-dev &&
            sudo -u postgres createuser -d -R -S $USER &&
            createdb $USER 
            python3 odoo-bin --addons-path=addons -d mydb "


# deploy:
#     stage: deploy
#     before_script:
#         - chmod 400 $SSH_KEY
#     script:
#         - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@3.239.93.125 "
#             sudo apt update;
#             sudo apt install -y docker.io;
#             sudo usermod -aG docker ubuntu;
#             sudo systemctl restart docker;
# if [ -n "$(docker ps -aq)" ]; then
#             docker ps -aq | xargs docker stop | xargs docker docker rm 
#             else 
#             docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG 
#             fi ;
#             docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
#             docker ps -aq | xargs docker stop | xargs docker docker rm &&
#             docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG &&
#             echo $USER"